//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDevGrp.OSIntranet.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDevGrp.OSIntranet.Gui.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account group with the unique number &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string AccountGroupNotFound {
            get {
                return ResourceManager.GetString("AccountGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The budget account group with the unique number &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string BudgetAccountGroupNotFound {
            get {
                return ResourceManager.GetString("BudgetAccountGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing the command &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting value of the property named &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorWhileGettingPropertyValue {
            get {
                return ResourceManager.GetString("ErrorWhileGettingPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while setting value of the property named &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorWhileSettingPropertyValue {
            get {
                return ResourceManager.GetString("ErrorWhileSettingPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal value for &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string IllegalArgumentValue {
            get {
                return ResourceManager.GetString("IllegalArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the configuration setting named &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidConfigurationSettingValue {
            get {
                return ResourceManager.GetString("InvalidConfigurationSettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in method &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string MethodError {
            get {
                return ResourceManager.GetString("MethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration setting named &apos;{0}&apos; is not defined..
        /// </summary>
        internal static string MissingConfigurationSetting {
            get {
                return ResourceManager.GetString("MissingConfigurationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in repository method &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string RepositoryError {
            get {
                return ResourceManager.GetString("RepositoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the resource named &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToLoadResource {
            get {
                return ResourceManager.GetString("UnableToLoadResource", resourceCulture);
            }
        }
    }
}
