//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDevGrp.OSIntranet.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDevGrp.OSIntranet.Gui.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string AccountingBalance {
            get {
                return ResourceManager.GetString("AccountingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountings.
        /// </summary>
        internal static string Accountings {
            get {
                return ResourceManager.GetString("Accountings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is overdrawn..
        /// </summary>
        internal static string AccountOverdrawnedWithoutValue {
            get {
                return ResourceManager.GetString("AccountOverdrawnedWithoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is overdrawn by {1}..
        /// </summary>
        internal static string AccountOverdrawnedWithValue {
            get {
                return ResourceManager.GetString("AccountOverdrawnedWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string AddBookkeeping {
            get {
                return ResourceManager.GetString("AddBookkeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address account.
        /// </summary>
        internal static string AddressAccount {
            get {
                return ResourceManager.GetString("AddressAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address accounts.
        /// </summary>
        internal static string AddressAccounts {
            get {
                return ResourceManager.GetString("AddressAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annex.
        /// </summary>
        internal static string Annex {
            get {
                return ResourceManager.GetString("Annex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual statement.
        /// </summary>
        internal static string AnnualStatement {
            get {
                return ResourceManager.GetString("AnnualStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asserts.
        /// </summary>
        internal static string Asserts {
            get {
                return ResourceManager.GetString("Asserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asserts total.
        /// </summary>
        internal static string AssertsTotal {
            get {
                return ResourceManager.GetString("AssertsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account ({0}).
        /// </summary>
        internal static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank accounts.
        /// </summary>
        internal static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeped.
        /// </summary>
        internal static string Bookkeeped {
            get {
                return ResourceManager.GetString("Bookkeeped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeped last month.
        /// </summary>
        internal static string BookkeepedLastMonth {
            get {
                return ResourceManager.GetString("BookkeepedLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeped last year.
        /// </summary>
        internal static string BookkeepedLastYear {
            get {
                return ResourceManager.GetString("BookkeepedLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeped year to date.
        /// </summary>
        internal static string BookkeepedYearToDate {
            get {
                return ResourceManager.GetString("BookkeepedYearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeping.
        /// </summary>
        internal static string Bookkeeping {
            get {
                return ResourceManager.GetString("Bookkeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget account.
        /// </summary>
        internal static string BudgetAccount {
            get {
                return ResourceManager.GetString("BudgetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget accounts.
        /// </summary>
        internal static string BudgetAccounts {
            get {
                return ResourceManager.GetString("BudgetAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget last month.
        /// </summary>
        internal static string BudgetLastMonth {
            get {
                return ResourceManager.GetString("BudgetLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget last year.
        /// </summary>
        internal static string BudgetLastYear {
            get {
                return ResourceManager.GetString("BudgetLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget year to date.
        /// </summary>
        internal static string BudgetYearToDate {
            get {
                return ResourceManager.GetString("BudgetYearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash ({0}).
        /// </summary>
        internal static string CachAccount {
            get {
                return ResourceManager.GetString("CachAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause.
        /// </summary>
        internal static string Cause {
            get {
                return ResourceManager.GetString("Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor.
        /// </summary>
        internal static string Creditor {
            get {
                return ResourceManager.GetString("Creditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditors.
        /// </summary>
        internal static string Creditors {
            get {
                return ResourceManager.GetString("Creditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be before or eqaul to {0}..
        /// </summary>
        internal static string DateGreaterThan {
            get {
                return ResourceManager.GetString("DateGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days when news is current.
        /// </summary>
        internal static string DaysForNews {
            get {
                return ResourceManager.GetString("DaysForNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor.
        /// </summary>
        internal static string Debtor {
            get {
                return ResourceManager.GetString("Debtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtors.
        /// </summary>
        internal static string Debtors {
            get {
                return ResourceManager.GetString("Debtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater or equal to {0}..
        /// </summary>
        internal static string DecimalLowerThan {
            get {
                return ResourceManager.GetString("DecimalLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has occurred.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling.
        /// </summary>
        internal static string ExceptionHandler {
            get {
                return ResourceManager.GetString("ExceptionHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        internal static string Experiences {
            get {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household.
        /// </summary>
        internal static string Household {
            get {
                return ResourceManager.GetString("Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing cont.
        /// </summary>
        internal static string HousingCost {
            get {
                return ResourceManager.GetString("HousingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurances.
        /// </summary>
        internal static string Insurances {
            get {
                return ResourceManager.GetString("Insurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a legal URI value..
        /// </summary>
        internal static string InvalidValueForUri {
            get {
                return ResourceManager.GetString("InvalidValueForUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year ({0}).
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities.
        /// </summary>
        internal static string Liabilities {
            get {
                return ResourceManager.GetString("Liabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities total.
        /// </summary>
        internal static string LiabilitiesTotal {
            get {
                return ResourceManager.GetString("LiabilitiesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan ({0}).
        /// </summary>
        internal static string LoanAccount {
            get {
                return ResourceManager.GetString("LoanAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        internal static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale data file.
        /// </summary>
        internal static string LocaleDataFile {
            get {
                return ResourceManager.GetString("LocaleDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly statement.
        /// </summary>
        internal static string MonthlyStatement {
            get {
                return ResourceManager.GetString("MonthlyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsMultiple {
            get {
                return ResourceManager.GetString("NewsMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of accounting lines to get.
        /// </summary>
        internal static string NumberOfAccountingLinesToGet {
            get {
                return ResourceManager.GetString("NumberOfAccountingLinesToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting warning.
        /// </summary>
        internal static string PostingWarning {
            get {
                return ResourceManager.GetString("PostingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting warnings.
        /// </summary>
        internal static string PostingWarnings {
            get {
                return ResourceManager.GetString("PostingWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyHeader {
            get {
                return ResourceManager.GetString("PrivacyPolicyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application does not collect or transmit any user’s personal information, with the exception of technical information included in HTTP requests (such as your IP address). No personal information is used, stored, secured or disclosed by services this application works with..
        /// </summary>
        internal static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private accounting.
        /// </summary>
        internal static string PrivateAccounting {
            get {
                return ResourceManager.GetString("PrivateAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting endpoint for service.
        /// </summary>
        internal static string SupportingServiceUri {
            get {
                return ResourceManager.GetString("SupportingServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale data file for synchronization.
        /// </summary>
        internal static string SyncDataFile {
            get {
                return ResourceManager.GetString("SyncDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations, travels etc..
        /// </summary>
        internal static string Vacations {
            get {
                return ResourceManager.GetString("Vacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid date or in incorrect format..
        /// </summary>
        internal static string ValueIsNotDate {
            get {
                return ResourceManager.GetString("ValueIsNotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid decimal or in incorrect format..
        /// </summary>
        internal static string ValueIsNotDecimal {
            get {
                return ResourceManager.GetString("ValueIsNotDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required and can&apos;t be empty..
        /// </summary>
        internal static string ValueIsRequiered {
            get {
                return ResourceManager.GetString("ValueIsRequiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is outside the interval ({0} - {1})..
        /// </summary>
        internal static string ValueOutsideInterval {
            get {
                return ResourceManager.GetString("ValueOutsideInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles, transport etc..
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wages.
        /// </summary>
        internal static string Wages {
            get {
                return ResourceManager.GetString("Wages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year to date ({0}).
        /// </summary>
        internal static string YearToDate {
            get {
                return ResourceManager.GetString("YearToDate", resourceCulture);
            }
        }
    }
}
